# Generated by Django 5.0.2 on 2024-02-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_category_alter_customer_gender_product_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ratingId',
        ),
    ]
