# Generated by Django 5.0.2 on 2024-03-02 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_remove_product_ratingid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.AddField(
            model_name='rating',
            name='customerId',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='eapp.customer'),
        ),
    ]
